# Generated by Django 2.0.2 on 2018-05-31 21:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=500)),
                ('tytul', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('data_utworzenia', models.DateTimeField(default=datetime.datetime(2018, 5, 31, 21, 4, 29, 616647, tzinfo=utc))),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('data_utworzenia', models.DateTimeField(default=datetime.datetime(2018, 5, 31, 21, 4, 29, 616647, tzinfo=utc))),
                ('data_publikacji', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='komentarz',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarz', to='blog.Post'),
        ),
    ]
