# Generated by Django 2.0.2 on 2018-05-31 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180531_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 22, 4, 8, 850873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 22, 4, 8, 850873, tzinfo=utc)),
        ),
    ]
