# Generated by Django 2.0.2 on 2018-06-01 06:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180601_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='data_utworzenia',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 6, 46, 21, 132555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_utworzenia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
