# Generated by Django 2.0.2 on 2018-06-01 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180601_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='data_utworzenia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='blog.Post'),
        ),
    ]
