# Generated by Django 2.0.2 on 2018-06-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180601_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentarz',
            name='tytul',
        ),
    ]
