lista = [1,2,3,4,5]
lista.extend([6,7])
print(lista)
lista.insert(0,0)
print(lista)
lista.remove(7)
print(lista)
lista.pop(0)
print(lista)
lista.pop(len(lista)-1)
print(lista)
lista.extend(lista)
print(lista)
lista.sort()
print(lista)
print(len(lista))
